# Generated by Django 3.2 on 2022-08-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер блока')),
                ('price', models.IntegerField(verbose_name='Стоимость за квадратный метр')),
                ('numb_entr', models.IntegerField(verbose_name='Количесвто подъездов')),
                ('numb_floor', models.IntegerField(verbose_name='Количесвто этажей')),
                ('numb_flat', models.IntegerField(verbose_name='Количесвто картир на этаже')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='ФИО владельца')),
                ('sale_date', models.IntegerField(blank=True, null=True, verbose_name='Дата продажи')),
                ('status', models.CharField(choices=[('Выкуп', 'Выкуп'), ('Выкуп не до конца', 'Выкуп не до конца'), ('Расторгнуто', 'Расторгнуто'), ('Не продано', 'Не продано')], max_length=100, verbose_name='Статус')),
                ('tot_area', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.block', verbose_name='Блок')),
            ],
        ),
    ]
