# Generated by Django 3.2 on 2022-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220823_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='sale_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
